$ErrorActionPreference = 'Stop'
$resourceRoot = Join-Path $PSScriptRoot '..\site\resources'
$domains = [ordered]@{ business='Business'; education='Education'; legal='Legal'; medical='Medical' }
$targets = [ordered]@{ individual='Individuals'; organization='Organizations'; team='Teams' }
$levels = [ordered]@{ learn='Learn'; apply='Apply'; augment='Augment' }

function Get-PageShell([string]$title, [string]$description, [string]$body, [string]$canonical) {
@"
<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>$title | Paidar.ai Resources</title><meta name="description" content="$description"><link rel="canonical" href="https://paidar.ai$canonical"><link rel="stylesheet" href="/assets/css/paidar.css"></head>
<body><a class="skip-link" href="#main">Skip to content</a><header class="site-header"><div class="container flex between center"><a class="brand" href="/"><img src="/assets/img/paidar.svg" alt="Paidar.ai logo" width="64" height="25"></a><button class="nav-toggle" aria-expanded="false" aria-controls="primary-nav" aria-label="Toggle navigation">Menu</button><nav id="primary-nav" class="primary-nav" aria-label="Primary"><ul class="nav-list nav-reset"><li><a href="/services.html">Services</a></li><li><a href="/assessments.html">Assessments</a></li><li><a href="/workshops/">Workshops</a></li><li><a href="/books/">Books</a></li><li><a href="/about.html">About</a></li><li><a class="btn btn-primary" href="/contact.html">Contact</a></li></ul></nav></div></header><main id="main">$body</main><footer class="site-footer"><div class="footer-grid"><div class="footer-socials" aria-label="Follow us"><a href="https://www.youtube.com/@embracingdigital" aria-label="YouTube" target="_blank" rel="noopener"><img src="/assets/img/youtube.svg" alt="YouTube" width="48" height="48"></a> <a href="https://www.linkedin.com/company/embracing-digital-transformation" aria-label="LinkedIn" target="_blank" rel="noopener"><img src="/assets/img/linkedin.svg" alt="LinkedIn" width="48" height="48"></a></div><div class="footer-brand"><img src="/assets/img/paidar.svg" alt="Paidar.ai logo" width="120" height="48"><div class="brand-name">Paidar.ai</div><small>&copy; <span id="y"></span> Paidar Systems LLC</small></div><nav aria-label="Footer" class="footer-nav"><ul class="nav-reset"><li><a href="/resources/">Resources</a></li><li><a href="/frameworks/">Frameworks</a></li><li><a href="/contact.html">Contact</a></li></ul></nav></div></footer><script src="/assets/js/main.js"></script></body></html>
"@
}

foreach ($domainKey in $domains.Keys) { foreach ($targetKey in $targets.Keys) { foreach ($levelKey in $levels.Keys) {
    $path = Join-Path $resourceRoot "$domainKey\$targetKey\$levelKey"
    New-Item -ItemType Directory -Path $path -Force | Out-Null
    $domain = $domains[$domainKey]; $target = $targets[$targetKey]; $level = $levels[$levelKey]
    $base = "/resources/$domainKey/$targetKey/$levelKey/"
    $assetTitle = "$domain AI resource for $target"
    $indexBody = @"
<section class="hero"><div class="container"><span class="eyebrow">$domain - $target - $level</span><h1>$assetTitle</h1><p class="lead">A practical resource for $target working in $domain at the $level stage of AI adoption.</p><nav class="resource-nav" aria-label="Resource stages"><a href="./">Overview</a><a href="learn.html">Learn</a><a href="apply.html">Apply</a><a href="augment.html">Augment</a><a href="augent.html">Augent</a></nav></div></section><section class="section"><div class="container grid-2"><div><span class="eyebrow">Asset description</span><h2>What this resource helps you do</h2><p>Use this page to describe the specific asset, its intended outcome, and the situation it addresses for $target in $domain. Add source material, prerequisites, and success measures here.</p><ul class="feature-list"><li>Define the problem and the people affected by it.</li><li>Make the work visible, repeatable, and easier to improve.</li><li>Set clear boundaries for responsible AI use.</li></ul></div><div class="card accent-ai"><h3>At a glance</h3><p><strong>Domain:</strong> $domain</p><p><strong>Audience:</strong> $target</p><p><strong>Stage:</strong> $level</p><p><strong>Asset type:</strong> Add the asset type here.</p></div></div></section><section class="section tint theme-modern"><div class="container"><span class="eyebrow">Use the companion pages</span><h2>Move from understanding to execution</h2><div class="grid-3"><article class="card"><h3>Learn</h3><p>Build shared language and understand the core ideas.</p><a class="arrow" href="learn.html">Open Learn</a></article><article class="card"><h3>Apply</h3><p>Use the ideas in a concrete workflow or decision.</p><a class="arrow" href="apply.html">Open Apply</a></article><article class="card"><h3>Augment</h3><p>Identify useful AI support and the checks that keep work reliable.</p><a class="arrow" href="augment.html">Open Augment</a></article></div></div></section>
"@
    Set-Content -LiteralPath (Join-Path $path 'index.html') -Value (Get-PageShell $assetTitle "A $domain resource for $target at the $level stage of AI adoption." $indexBody $base) -Encoding utf8
    foreach ($stageKey in $levels.Keys) {
        $stage = $levels[$stageKey]; $stageTitle = "${stage}: $assetTitle"
        $stageBody = @"
<section class="hero"><div class="container"><span class="eyebrow">$domain - $target - $stage</span><h1>$stageTitle</h1><p class="lead">Use this companion page to develop the $stage portion of the resource for $target in $domain.</p><nav class="resource-nav" aria-label="Resource stages"><a href="./">Overview</a><a href="learn.html">Learn</a><a href="apply.html">Apply</a><a href="augment.html">Augment</a><a href="augent.html">Augent</a></nav></div></section><section class="section"><div class="container grid-2"><div><span class="eyebrow">Build this section</span><h2>Describe the $stage experience</h2><p>Replace this starter content with the asset's $stage guidance. Explain the intended action, include a concrete example, and name the evidence or review needed before moving forward.</p><ol class="step-list"><li><strong>Frame the work.</strong> State the outcome and the constraints.</li><li><strong>Work through an example.</strong> Connect the guidance to $domain.</li><li><strong>Check the result.</strong> Define what good and safe look like.</li></ol></div><aside class="card accent-edge"><h3>Authoring prompt</h3><p>What should someone in the $target audience be able to do after completing this $stage page?</p><a class="btn btn-outline" href="./">Back to asset overview</a></aside></div></section><section class="section tint theme-data"><div class="container"><h2>Related stages</h2><div class="flex wrap"><a class="btn btn-primary" href="learn.html">Learn</a><a class="btn btn-primary" href="apply.html">Apply</a><a class="btn btn-primary" href="augment.html">Augment</a><a class="btn btn-primary" href="augent.html">Augent</a></div></div></section>
"@
        Set-Content -LiteralPath (Join-Path $path "$stageKey.html") -Value (Get-PageShell $stageTitle "The $stage stage of a $domain resource for $target." $stageBody "$base$stageKey.html") -Encoding utf8
    }
    Set-Content -LiteralPath (Join-Path $path 'augent.html') -Value (Get-PageShell "Augent: $assetTitle" "The requested augent companion page for a $domain resource for $target." '<meta http-equiv="refresh" content="0; url=augment.html"><section class="section"><div class="container"><h1>Augent</h1><p>This requested spelling is retained as a compatibility link. The canonical companion page is <a class="arrow" href="augment.html">Augment</a>.</p></div></section>' "$base$stageKey.html") -Encoding utf8
} } }
Write-Output "Generated resource matrix at $resourceRoot"
